# This file was generated by the `rspec --init` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# Require this file using `require "spec_helper"` to ensure that it is only
# loaded once.
#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration

require 'simplecov'
require 'simplecov-rcov'

SimpleCov.use_merging
SimpleCov.merge_timeout(10000)
SimpleCov.command_name('adheres-to-policy-gem')
SimpleCov.start('test_frameworks') do
  SimpleCov.coverage_dir('../../coverage')
  SimpleCov.at_exit {
    SimpleCov.result
  }
end

require 'adheres_to_policy'

RSpec.configure do |config|
  config.treat_symbols_as_metadata_keys_with_true_values = true
  config.run_all_when_everything_filtered = true
  config.filter_run :focus
  config.order = 'random'

  config.after(:each) do
    Rails.cache.clear
    # Clean up after ourselves since its a class instance variable
    AdheresToPolicy::Cache.instance_variable_set(:@cache, nil)
  end
end

module Rails
  def self.cache
    @cache ||= ActiveSupport::Cache::MemoryStore.new
  end
end