# This file was generated by the `rspec --init` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# Require this file using `require "spec_helper"` to ensure that it is only
# loaded once.
#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration

begin
  require '../../spec/coverage_tool.rb'
  CoverageTool.start("adheres-to-policy-gem")
rescue LoadError => e
  puts "Error: #{e}"
end

require 'adheres_to_policy'

RSpec.configure do |config|
  config.run_all_when_everything_filtered = true
  config.filter_run :focus
  config.order = 'random'

  config.after(:each) do
    Rails.cache.clear
    # Clean up after ourselves since its a class instance variable
    AdheresToPolicy::Cache.instance_variable_set(:@cache, nil)
  end
end

module Rails
  def self.cache
    @cache ||= ActiveSupport::Cache::MemoryStore.new
  end
end
