FROM local/yarn-runner

RUN --mount=type=bind,from=local/cache-helper,source=/tmp/dst,target=/cache-helper \
  tar --no-same-owner -xf /cache-helper/webpack-builder.tar -C ${APP_HOME}
RUN yarn build:packages
