# it is intended that this be used exclusive of all other docker-compose.*yml files in CI
version: "2.1"
services:
  web:
    # use master if NAME is unavailable
    image: "${PATCHSET_TAG}"
    volumes:
      - ".git:/usr/src/app/.git"
