# frozen_string_literal: true

source "https://rubygems.org"

gemspec

path ".." do
  gem "canvas_cache"
  gem "canvas_errors"
  gem "config_file"
  gem "dynamic_settings"
end

eval_gemfile("../gemfile_prefix.rb")

gem "debug"
gem "rspec"
gem "timecop"
