source 'https://rubygems.org'

gem 'canvas_sort', :path => '../canvas_sort'
gem 'canvas_http', :path => '../canvas_http'
gem 'canvas_slug', :path => '../canvas_slug'
gem 'multipart', :path => '../multipart'

gemspec
