# frozen_string_literal: true

source "https://rubygems.org"

gem "canvas_http", path: "../canvas_http"
gem "canvas_slug", path: "../canvas_slug"
gem "canvas_sort", path: "../canvas_sort"
gem "multipart", path: "../multipart"

gemspec
