source 'https://rubygems.org'

# Specify your gem's dependencies in canvas_stringex.gemspec
gemspec

gem 'rails', :github => 'makandra/rails', :branch => '2-3-lts', :ref => 'e86daf8ff727d5efc0040c876ba00c9444a5d915'