module I18nTasks
  module Utils
    CORE_KEYS = %i[date time number datetime support].freeze

    def self.dump_js(translations)
      <<-TRANSLATIONS.gsub(/^ {8}/, '')
        // this file was auto-generated by rake i18n:generate_js.
        // you probably shouldn't edit it directly
        define(['i18nObj', 'jquery'], function(I18n, $) {
          $.extend(true, I18n, {translations: #{translations.to_ordered.to_json}});
        });
      TRANSLATIONS
    end
  end
end
