production:
  domain: <%= ENV.fetch('CANVAS_PROD_DOMAIN', 'canvas-web.' + ENV.fetch('INST_DOMAIN','inseng.test')) %>

test:
  domain: localhost

development:
  domain: <%= ENV.fetch('CANVAS_DEV_DOMAIN', 'canvas-web.' + ENV.fetch('INST_DOMAIN','inseng.test')) %>
  files_domain: <%= ENV.fetch('CANVAS_DEV_DOMAIN', 'canvas-web.' + ENV.fetch('INST_DOMAIN','inseng.test')) %>
