require([
  'specs/TemplateSpec',
  'specs/CustomListSpec',
  'specs/invokerSpec',
  'specs/jQuery.instructureMiscPluginsSpec',
  'specs/userNamePartsSpec',
  'specs/objectCollectionSpec',
  'specs/util/BackoffPollerSpec',
  'specs/jQuery.instructureJqueryPatches',
  'specs/ENVSpec'
]);
