require([
  'specs/TemplateSpec',
  'specs/CustomListSpec',
  'specs/invokerSpec',
  'specs/jQuery.instructureMiscPluginsSpec',
  'specs/userNamePartsSpec',
  'specs/objectCollectionSpec',
  'specs/helpDialogSpec',
  'specs/paginatedListSpec',
  'specs/util/BackoffPollerSpec',
  'specs/jQuery.instructureJqueryPatchesSpec',
  'specs/ENVSpec',
  'specs/calendar/TimeBlockListManagerSpec',
  'specs/calendar/TimeBlockListSpec',
  'specs/calendar/TimeBlockRowSpec',
  'specs/util/processMigrationItemSelectionsSpec',
  'specs/util/processItemSelectionsSpec'
]);

