source 'https://rubygems.org'

# Specify your gem's dependencies in canvas_time.gemspec
gemspec

require File.expand_path("../../../config/canvas_rails4", __FILE__)

if CANVAS_RAILS3
  gem 'activesupport', '~> 3.2.0'
end
