/*
 * Copyright (C) 2021 - present Instructure, Inc.
 *
 * This file is part of Canvas.
 *
 * Canvas is free software: you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License as published by the Free
 * Software Foundation, version 3 of the License.
 *
 * Canvas is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
 * A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License along
 * with this program. If not, see <http://www.gnu.org/licenses/>.
 */

/*
 * this file is generated by scripts/getTranslationGetters. do not edit
 */

export default function getTinymceTranslations(locale) {
  let p
  switch (locale) {
    case 'ar_SA':
      p = import('./rce/languages/ar_SA')
      break
    case 'bg_BG':
      p = import('./rce/languages/bg_BG')
      break
    case 'ca':
      p = import('./rce/languages/ca')
      break
    case 'cs':
      p = import('./rce/languages/cs')
      break
    case 'cy':
      p = import('./rce/languages/cy')
      break
    case 'da':
      p = import('./rce/languages/da')
      break
    case 'de':
      p = import('./rce/languages/de')
      break
    case 'el':
      p = import('./rce/languages/el')
      break
    case 'en_GB':
      p = import('./rce/languages/en_GB')
      break
    case 'es':
      p = import('./rce/languages/es')
      break
    case 'fa_IR':
      p = import('./rce/languages/fa_IR')
      break
    case 'fr_FR':
      p = import('./rce/languages/fr_FR')
      break
    case 'he_IL':
      p = import('./rce/languages/he_IL')
      break
    case 'hu_HU':
      p = import('./rce/languages/hu_HU')
      break
    case 'hy':
      p = import('./rce/languages/hy')
      break
    case 'it':
      p = import('./rce/languages/it')
      break
    case 'ja':
      p = import('./rce/languages/ja')
      break
    case 'ko_KR':
      p = import('./rce/languages/ko_KR')
      break
    case 'nb_NO':
      p = import('./rce/languages/nb_NO')
      break
    case 'nl':
      p = import('./rce/languages/nl')
      break
    case 'pl':
      p = import('./rce/languages/pl')
      break
    case 'pt_BR':
      p = import('./rce/languages/pt_BR')
      break
    case 'pt_PT':
      p = import('./rce/languages/pt_PT')
      break
    case 'ro':
      p = import('./rce/languages/ro')
      break
    case 'ru_RU':
      p = import('./rce/languages/ru_RU')
      break
    case 'sr':
      p = import('./rce/languages/sr')
      break
    case 'sv_SE':
      p = import('./rce/languages/sv_SE')
      break
    case 'tr_TR':
      p = import('./rce/languages/tr_TR')
      break
    case 'uk_UA':
      p = import('./rce/languages/uk_UA')
      break
    case 'vi_VN':
      p = import('./rce/languages/vi_VN')
      break
    case 'zh_CN':
      p = import('./rce/languages/zh_CN')
      break
    case 'zh_TW':
      p = import('./rce/languages/zh_TW')
      break
    default:
      p = Promise.resolve(null)
  }
  p.then(() => {}).catch(err => {
    console.error('Failed loading ', locale, err)
  })
  return p
}
