require ['compiled/util/processMigrationItemSelections'], (processMigrationItemSelections)->
  module "processMigrationItemSelections"
  test 'change hash of hashes to hash of lists', ->
    data = {
            "authenticity_token": "QL/bXYKYG65JrbPhnzd5XXwNMmRw2kbsl+j02gY3Quc=", 
            "copy[content_migration_id]": "219", 
            "copy[everything]": "1", 
            "copy[all_assignments]": "1", 
            "copy[assignments][id]": "1", 
            "copy[all_quizzes]": "1", 
            "copy[quizzes][id]": "1", 
            "copy[quizzes][res00026]": "1", 
            "copy[quizzes][res00027]": "1", 
            "copy[quizzes][res00028]": "0",
            "copy[assessment_questions]": "1", 
            "copy[all_files]": "1", 
            "copy[folders][id]": "0", 
            "copy[files][id]": "0", 
            "copy[all_modules]": "1", 
            "copy[modules][id]": "1", 
            "copy[all_outline_folders]": "1", 
            "copy[outline_folders][id]": "1", 
            "copy[outline_folders][toc00001]": "0", 
            "copy[outline_folders][res00006]": "1", 
            "copy[outline_folders][res00008]": "1",
            "copy[all_topics]": "1", 
            "copy[topics][id]": "1", 
            "copy[all_announcements]": "1", 
            "copy[all_calendar_events]": "1", 
            "copy[all_rubrics]": "1", 
            "copy[all_groups]": "1", 
            "copy[groups][id]": "1", 
            "copy[all_assignment_groups]": "1", 
            "copy[assignment_groups][id]": "1",
            "copy[all_wikis]": "1", 
            "copy[wikis][id]": "1", 
            "copy[all_external_tools]": "1", 
            "copy[external_tools][id]": "1", 
            "copy[shift_dates]": "1", 
            "copy[old_start_date]": "Nov 6, 2009", 
            "copy[old_end_date]": "Nov 6, 2009", 
            "copy[new_start_date]": "",
            "copy[new_end_date]": ""
    }
    newData = processMigrationItemSelections(data)
    deepEqual newData, {
                        "items_to_copy":{
                          "assignments": ["id"],
                          "quizzes": ["id","res00026","res00027"],
                          "modules": ["id"],
                          "outline_folders": ["id","res00006","res00008"],
                          "topics": ["id"],
                          "groups": ["id"],
                          "assignment_groups": ["id"],
                          "wikis": ["id"],
                          "external_tools": ["id"]
                          },
                        "authenticity_token": "QL/bXYKYG65JrbPhnzd5XXwNMmRw2kbsl+j02gY3Quc=",
                        "copy[content_migration_id]": "219",
                        "copy[everything]": "1",
                        "copy[all_assignments]": "1",
                        "copy[all_quizzes]": "1",
                        "copy[assessment_questions]": "1",
                        "copy[all_files]": "1",
                        "copy[all_modules]": "1",
                        "copy[all_outline_folders]": "1",
                        "copy[all_topics]": "1",
                        "copy[all_announcements]": "1",
                        "copy[all_calendar_events]": "1",
                        "copy[all_rubrics]": "1",
                        "copy[all_groups]": "1",
                        "copy[all_assignment_groups]": "1",
                        "copy[all_wikis]": "1",
                        "copy[all_external_tools]": "1",
                        "copy[shift_dates]": "1",
                        "copy[old_start_date]": "Nov 6, 2009",
                        "copy[old_end_date]": "Nov 6, 2009",
                        "copy[new_start_date]": "",
                        "copy[new_end_date]": ""
    }
    
    