test:
  adapter: postgresql
  encoding: utf8
  database: <%= ENV['RAILS_DB_NAME_TEST'] %>
  host: <%= ENV['RAILS_DB_HOST'] %>
  password: <%= ENV['RAILS_DB_PASS'] %>
  username: postgres
  timeout: 5000
  shard_name: public
  schema_search_path: "''"
  shard1: canvas_test_shard_1
  shard2: canvas_test_shard_2
  use_qualified_names: true
