common: &common
  encryption_key: <%= ENV.fetch("ENCRYPTION_KEY", 'tEmtL3NHrF+Z/bwkDXGRav/D7FU=') %>

development:
  <<: *common

test:
  <<: *common
  lti_iss: 'https://canvas.instructure.com'

production:
  <<: *common
