# to use this add docker-compose/pulsar.yml
# to your COMPOSE_FILE var in .env
version: "2.3"

services:
  postgres:
    environment:
      REPLICATION_USER: impulse
      REPLICATION_PASSWORD: impulse
      REPLICATION_DB: canvas
  web:
    depends_on:
      - pulsar
  pulsar:
    image: apachepulsar/pulsar:latest
    command: bin/pulsar standalone
    ports:
      - "6650"
      - "8080"
    volumes:
      - pulsar-data:/pulsar/data
  pulsar-admin:
    image: apachepulsar/pulsar:latest
    volumes:
      - ./docker-compose/pulsar:/pulsar/scripts
    depends_on:
      - pulsar

volumes:
  pulsar-data: {}