# frozen_string_literal: true

source "https://rubygems.org"

# Declare your gem's dependencies in broadcast_policy.gemspec.
# Bundler will treat runtime dependencies like base dependencies, and
# development dependencies will be added by default to the :development group.
gemspec

eval_gemfile("../gemfile_prefix.rb")
