# Uncomment to enable cassandra
# see canvas/config/cassandra.yml.example for further instructions

# default: &default
#   page_views:
#     servers:
#     - cassandra:9160
#     keyspace: page_views
#   auditors:
#     servers:
#     - cassandra:9160
#     keyspace: auditors

# development:
#   <<: *default

# test:
#   <<: *default
#   page_views:
#     keyspace: page_views_test
#   auditors:
#     keyspace: auditors_test

# production:
#   <<: *default%
