default: &default
  domain: <%= ENV.fetch('CANVAS_DOMAIN', 'canvas.docker') %>
  ssl: <%= ENV.fetch('CANVAS_DOMAIN_SSL', false) %>

development:
  <<: *default

production:
  <<: *default

test:
  <<: *default
