default: &default
  servers:
    - <%= ENV.fetch('REDIS_SERVER', 'redis://redis') %>

development:
  <<: *default

test:
  # only tests that are exercising the integration with redis require redis to run.
  # warning: the redis database will get cleared before each test, so if you
  # use this server for anything else, make sure to set aside a database id for
  # these tests to use.
  <<: *default
  db: <%= ENV.fetch('PARALLEL_INDEX', '1') %>

production:
  <<: *default

