# default: &default
#   addr: <%= ENV.fetch('REDIS_VAULT_ADDR', 'http://vault:8200') %>
#   token: <%= ENV.fetch('REDIS_VAULT_TOKEN', 'canvas_root_token') %>
#   kv_mount: <%= ENV.fetch('REDIS_VAULT_KV_MOUNT', 'app-canvas') %>

# development:
#   <<: *default

# test:
#   <<: *default

# production:
#   <<: *default
