# frozen_string_literal: true

#
# Copyright (C) 2026 - present Instructure, Inc.
#
# This file is part of Canvas.
#
# Canvas is free software: you can redistribute it and/or modify it under
# the terms of the GNU Affero General Public License as published by the Free
# Software Foundation, version 3 of the License.
#
# Canvas is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
# details.
#
# You should have received a copy of the GNU Affero General Public License along
# with this program. If not, see <http://www.gnu.org/licenses/>.
#

describe "routes" do
  let(:req) { ActionDispatch::Request.new({}) }

  # Default actions generated by `resources` declarations. Controllers
  # frequently only implement a subset, so unimplemented defaults are
  # not treated as errors.
  let(:default_resource_actions) do
    ActionDispatch::Routing::Mapper::Resources::Resource.default_actions(false).to_set(&:to_s)
  end

  it "all point to valid controllers and actions" do
    Rails.application.eager_load!

    errors = []

    Rails.application.routes.routes.each do |route|
      defaults = route.defaults
      next unless defaults[:controller] && defaults[:action]

      controller_name = defaults[:controller]
      action_name = defaults[:action]

      key = "#{controller_name}##{action_name}"

      controller_class = begin
        req.controller_class_for(controller_name)
      rescue NameError
        errors << "#{route.verb} #{route.path.spec} maps to non-existent controller: #{key}"
        next
      end

      next unless controller_class.action_methods.exclude?(action_name)
      next if default_resource_actions.include?(action_name)

      errors << "#{key} (#{route.verb} #{route.path.spec}) is not defined"
    end

    expect(errors).to be_empty, "Dangling routes found:\n  #{errors.join("\n  ")}"
  end
end
