source 'https://rubygems.org'
gemspec

require File.expand_path("../../../config/canvas_rails4", __FILE__)

if CANVAS_RAILS3
  gem 'activerecord', '~> 3.2.0'
else
  gem 'activerecord', '~> 4.0.0'
end
