#!/usr/bin/env node

var path = require('path');
var root = path.join(__dirname, '..');
var grunt;

// Use the app root as the CWD so that grunt can read the Gruntfile there:
process.chdir(root);

// Make sure we load the development tasks (override any CLI flags):
process.env.production = false;
process.env.NODE_ENV = 'development';

// Run the "test" grunt task:
grunt = require(path.join(root, 'node_modules', 'grunt', 'lib', 'grunt'));
grunt.tasks('test');