#!/bin/bash

set -e

PATH=/var/lib/gems/1.8/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
APPROOT=/var/rails/canvas-lms
HOME=/var/lib/canvas-lms

[ -f "$APPROOT/config/environment.rb" ] || exit 0

# switch to app root
cd $APPROOT

# set up config
if [ -e "config/GEM_HOME" ]; then
  export GEM_HOME=$(cat config/GEM_HOME)
fi

. /usr/share/debconf/confmodule

function get_config {
  db_get "$1" || exit 1
  echo "$RET" | sed 's/"//g' | sed 's/\\//g'
}

if ! [ "$(id -u)" == "0" ]; then
  echo must be run either via sudo or root
  exit 1
fi

exec su $(stat -c %U "$APPROOT/config/environment.rb") -c "/usr/bin/env \
PATH=\"$PATH\" \
HOME=\"$HOME\" \
GEM_HOME=\"$GEM_HOME\" \
RAILS_ENV=production \
CANVAS_LMS_ADMIN_EMAIL=\"$(get_config canvas-lms/admin-email)\" \
CANVAS_LMS_ADMIN_PASSWORD=\"$(get_config canvas-lms/admin-password)\" \
CANVAS_LMS_STATS_COLLECTION=\"$(get_config canvas-lms/collect-stats)\" \
CANVAS_LMS_ACCOUNT_NAME=\"$(get_config canvas-lms/default-account-name)\" \
/usr/bin/env \
bundle exec rake db:initial_setup"

exit 1
