development:
  bucket_name: "<%= ENV['S3_BUCKET_NAME'] %>"
  access_key_id: "<%= ENV['S3_ACCESS_KEY_ID'] %>"
  secret_access_key: "<%= ENV['S3_ACCESS_KEY'] %>"
  region: "<%= ENV['AWS_REGION'] %>"

test:
  bucket_name: "<%= ENV['S3_BUCKET_NAME'] %>"
  access_key_id: "<%= ENV['S3_ACCESS_KEY_ID'] %>"
  secret_access_key: "<%= ENV['S3_ACCESS_KEY'] %>"
  region: "<%= ENV['AWS_REGION'] %>"

production:
  bucket_name: "<%= ENV['S3_BUCKET_NAME'] %>"
  access_key_id: "<%= ENV['S3_ACCESS_KEY_ID'] %>"
  secret_access_key: "<%= ENV['S3_ACCESS_KEY'] %>"
  region: "<%= ENV['AWS_REGION'] %>"
