development:
  bucket_name: development-bucket
  access_key_id: access_key
  secret_access_key: secret_key
  region: us-east-1

test:
  bucket_name: test-bucket
  access_key_id: access_key
  secret_access_key: secret_key
  region: us-east-1
  
production:
  bucket_name: nterone-lms
  access_key_id: AKIAQF3JKPJVPUPFSSMS
  secret_access_key: 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
  region: us-east-1