source 'https://rubygems.org'

gemspec

gem 'paginated_collection', path: '../paginated_collection'
gem 'json_token', path: '../json_token'

require File.expand_path("../../../config/canvas_rails4_2", __FILE__)

if CANVAS_RAILS4_0
  gem 'rails', '~> 4.0.13'
end