openapi: 3.1.0
info:
  title: Dynamic Registration
  description: TBD
  version: 0.1.0
paths:
  /api/lti/accounts/:account_id/registration_token:
    get:
      summary: TBD
      responses:
        200:
          description: TBD
          content:
            application/json:
              schema:
                type: object
                properties:
                  uuid:
                    type: string
                  oidc_configuration_url:
                    type: string
                  token:
                    type: string
        401:
          description: TBD
  /api/lti/accounts/:account_id/registrations/uuid/:registration_uuid:
    get:
      summary: TBD
      parameters:
        - in: path
          name: registration_uuid
          required: true
          schema:
            type: string
      responses:
        200:
          description: TBD
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/registration"
        401:
          description: TBD
        404:
          description: TBD
  /api/lti/accounts/:account_id/lti_registrations/uuid/:registration_uuid:
    get:
      summary: TBD
      parameters:
        - in: path
          name: registration_uuid
          required: true
          schema:
            type: string
      responses:
        200:
          description: TBD
          content:
            # We return an Lti::Registration object, but it's not the same as the Lti::IMS::Registration object.
            # Given that we're moving towards a different way of generating these API docs, we'll leave it blank.
            application/json:
              schema:
                type: object
        401:
          description: TBD
        404:
          description: TBD
  /api/lti/accounts/:account_id/lti_registration_update_request/uuid/:registration_uuid:
    get:
      summary: TBD
      parameters:
        - in: path
          name: registration_uuid
          required: true
          schema:
            type: string
      responses:
        200:
          description: TBD
          content:
            # We return an Lti::RegistrationUpdateRequest object
            application/json:
              schema:
                type: object
        401:
          description: TBD
        404:
          description: TBD
  /api/lti/accounts/:account_id/registrations/:registration_id:
    get:
      summary: TBD
      parameters:
        - in: path
          name: registration_id
          required: true
          schema:
            type: string
      responses:
        200:
          description: TBD
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/registration"
        401:
          description: TBD
  /api/lti/accounts/:account_id/registrations/:registration_id/overlay:
    put:
      summary: TBD
      parameters:
        - in: path
          name: registration_id
          required: true
          schema:
            type: string
      responses:
        200:
          description: TBD
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/overlay"
        401:
          description: TBD
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/registration"
  /api/lti/registrations:
    post:
      summary: TBD
      responses:
        '200':
          description: "The tool registration was created."
          content:
            application/json:
              schema:
                type: object
        '401':
          description: "The provided token was invalid."
        '422':
          description: "The lti tool registration configuration was invalid."
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                application_type:
                  type: string
                grant_types:
                  type: array
                response_types:
                  type: array
                redirect_uris:
                  type: array
                initiate_login_uri:
                  type: string
                client_name:
                  type: string
                jwks_uri:
                  type: string
                token_endpoint_auth_method:
                  type: string
                lti_tool_configuration:
                  type: object
                  properties:
                    domain:
                      type: string
                    messages:
                      type: array
                    claims:
                      type: array
                    target_link_uri:
                      type: string
  /api/lti/registrations/:registration_id:
    get:
      summary: Get Dynamic Registration Configuration
      description: >
        Retrieves the LTI Dynamic Registration configuration for a given registration.
        This endpoint provides the complete registration configuration including client details,
        scopes, redirect URIs, and LTI tool configuration. Authentication is required via
        developer key access token with appropriate LTI registration scopes.
      parameters:
        - in: path
          name: registration_id
          required: true
          schema:
            type: string
          description: The ID of the LTI IMS Registration to retrieve configuration for
      responses:
        '200':
          description: LTI Dynamic Registration configuration
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/dynamicRegistrationConfiguration"
        '401':
          description: "Unauthorized - invalid or missing access token"
          content:
            application/json:
              schema:
                type: object
                properties:
                  errorMessage:
                    type: string
        '404':
          description: "Registration not found"
      security:
        - developerKeyAuth: []
    put:
      summary: Updates an existing tool registration.
      parameters:
        - in: path
          name: registration_id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: "The tool registration was updated."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/registration"
        '401':
          description: "The provided token was invalid."
        '404':
          description: "The tool registration was not found."
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/registration"
  /api/lti/registrations/:registration_id/view:
    get:
      summary: Redirects the user to the tool's configuration view.
      parameters:
        - in: path
          name: registration_id
          required: true
          schema:
            type: string
      responses:
        '302':
          description: "The user was redirected to the tool's configuration view."
          headers:
            Location:
              schema:
                type: string
components:
  schemas:
    placement:
      enum: [course_navigation, account_navigation, user_navigation, assignment_selection, link_selection, editor_button, resource_selection, global_navigation]
    registration:
      type: object
      properties:
        id:
          type: string
        developer_key_id:
          type: string
        overlay:
          type: TODO
        lti_tool_configuration:
          claims:
            type: array
            items:
              type: string
          domain:
            type: string
          messages:
            type: array
            items:
              type: object
              properties:
                path:
                  type:
                    enum: [LtiResourceLinkRequest, LtiDeepLinkingRequest]
                label:
                  type: string
                roles:
                  type: array
                  items:
                    type: string
                icon_uri:
                  type: string
                placements:
                  type: array
                  items:
                    schema:
                      $ref: "#/components/schemas/placement"
                target_link_uri:
                  type: string
                custom_parameters:
                  type: object
                  additionalProperties:
                    type: string
          target_link_uri:
            type: string
        application_type:
          enum: [web]
        grant_types:
          type: array
          items:
            type: string
        response_types:
          type: array
          items:
            type: string
        redirect_uris:
          type: array
          items:
            type: string
        initiate_login_uri:
          type: string
        client_name:
          type: string
        jwks_uri:
          type: string
        logo_uri:
          type: string
        token_endpoint_auth_method:
          type: string
        contacts:
          type: array
          items:
            type: string
        client_uri:
          type: string
        policy_uri:
          type: string
        tos_uri:
          type: string
        scopes:
          type: array
          items:
            type: string
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
        guid:
          type: string
    overlay:
      type: object
      properties:
        disabeldPlacements:
          type: array
          items:
            schema:
              $ref: "#/components/schemas/placement"
        disabledScopes:
          type: array
          items:
            type: string
          placements:
            type: array
            items:
              schema:
                type: object
                properties:
                  type:
                    $ref: "#/components/schemas/placement"
                  enabled:
                    type: boolean
                  icon_url:
                    type: string
                  label:
                    type: string
    dynamicRegistrationConfiguration:
      type: object
      description: LTI Dynamic Registration configuration response
      properties:
        client_id:
          type: string
          description: The global developer key ID as a string
        application_type:
          type: string
          enum: [web]
          description: Always "web" for LTI registrations
        grant_types:
          type: array
          items:
            type: string
          description: Array of supported OAuth2 grant types
        initiate_login_uri:
          type: string
          description: URL for LTI login initiation
        redirect_uris:
          type: array
          items:
            type: string
          description: Array of allowed redirect URIs after authentication
        response_types:
          type: array
          items:
            type: string
            enum: [id_token]
          description: Array of supported OAuth2 response types (always "id_token")
        client_name:
          type: string
          description: Display name of the LTI tool
        jwks_uri:
          type: string
          description: URL to the tool's JSON Web Key Set
        logo_uri:
          type: string
          description: URL to the tool's logo/icon
        token_endpoint_auth_method:
          type: string
          enum: [private_key_jwt]
          description: Authentication method (always "private_key_jwt")
        scope:
          type: string
          description: Space-separated string of OAuth2 scopes including LTI scopes and "openid"
        https://purl.imsglobal.org/spec/lti-tool-configuration:
          type: object
          description: LTI tool configuration object with placements and Canvas-specific extensions
          properties:
            domain:
              type: string
            description:
              type: string
            target_link_uri:
              type: string
            claims:
              type: array
              items:
                type: string
            messages:
              type: array
              items:
                type: object
                properties:
                  type:
                    type: string
                  placements:
                    type: array
                    items:
                      type: string
            https://canvas.instructure.com/lti/registration_config_url:
              type: string
              description: URL to view/manage the registration in Canvas
        registration_client_uri:
          type: string
          description: URL to view/manage the registration in Canvas
        deployment_id:
          type: string
          description: The deployment ID for the root account deployment (if exists)
          nullable: true
      required:
        - client_id
        - application_type
        - grant_types
        - initiate_login_uri
        - redirect_uris
        - response_types
        - client_name
        - jwks_uri
        - token_endpoint_auth_method
        - scope
        - https://purl.imsglobal.org/spec/lti-tool-configuration
        - registration_client_uri
  securitySchemes:
    developerKeyAuth:
      type: http
      scheme: bearer
      description: Developer key access token with LTI registration scopes
