source "https://rubygems.org"

# Declare your gem's dependencies in moodle2cc.gemspec.
# Bundler will treat runtime dependencies like base dependencies, and
# development dependencies will be added by default to the :development group.
gemspec

