#!/usr/bin/env ruby
# frozen_string_literal: true

require_relative './linter'

linter_options = {
  linter_name: "brakeman",
  file_regex: /\.rb$/,
  format: 'brakeman',
  command: 'bundle exec brakeman --rails6 --quiet --format json --confidence-level 2',
  append_files_to_command: false,
}

brakeman = Linter.new(linter_options)
brakeman.run
