#!/usr/bin/env ruby

ENV['RUNNING_AS_DAEMON'] = 'true'
ENV['BUNDLE_GEMFILE'] ||= File.expand_path('../../Gemfile', __FILE__)
# We avoid loading the whole rails environment here, so that commands like
# `status` and `start` return much faster.
require 'bundler/setup'
require 'delayed_job'

Delayed::Pool.new.run()
