#!/usr/bin/env ruby
# frozen_string_literal: true

require_relative "linter"

linter_options = {
  file_regex: %r{^ui/.*\.(?:js|ts|tsx)$},
  linter_name: "eslint",
  format: "eslint",
  command: "node_modules/.bin/eslint",
  campsite_mode: false,
  boyscout_mode: false,
  append_files_to_command: true,
  severe_anywhere: true
}

eslint = Linter.new(linter_options)
eslint.run

puts "Linting sub-packages"

linter_options[:command] = "yarn lint"
linter_options[:base_dir] = "../../"
linter_options[:file_regex] = nil
linter_options[:severe_anywhere] = false

package_dirs = `ls -1 packages/*/package.json 2> /dev/null`.split("\n").map { |d| d.sub("/package.json", "") }
cwd = Dir.pwd
package_dirs.each do |d|
  puts "working sub-package dir #{d}"
  Dir.chdir d
  linter_options[:file_regex] = %r{#{d}/.*\.(?:js|ts|tsx)$}
  eslint = Linter.new(linter_options)
  eslint.run
  Dir.chdir cwd
end
