#!/bin/bash
set -e

# little shortcut for doing yarn install/update/whatever for each of our
# gems that do node-y stuff

# canvas (mis|ab)uses devDependencies, we try not to for these ones
# though... only get their prod deps by default. if you are testing/
# developing one of these, go into the dir and yarn there
export NODE_ENV=production

for path in $(ls -1 gems/{,plugins/}*/package.json 2> /dev/null); do
  pushd $(dirname $path) > /dev/null
  echo "running yarn $1 for $path"
  yarn $1
  popd > /dev/null
done
