#!/bin/bash
set -e

# A little shortcut for doing yarn install/update/whatever for each of our
# gems/local yarn packages that do node-y stuff

for path in $(ls -1 {gems/{,plugins/},packages/}*/package.json 2> /dev/null); do
  pushd $(dirname $path) > /dev/null

  if [[ $path = *"packages"* ]]; then
    # Because things in /packages need to be able to build themselves, we need
    # to make sure to also install their devDependences.
    NODE_ENV=development
  else
    # for gems w/ node modules only get their prod deps by default.
    # if you are testing / developing one of these, go into the dir and yarn there.
    NODE_ENV=production
  fi

  if [[ $path != *"packages"* && ($1 == "test" || $1 == "lint" || $1 == "build:canvas") ]]; then
    # yarn test and lint are packages directory specific commands
    popd > /dev/null
    continue
  fi

  echo "running yarn $1 for $path w/ NODE_ENV=$NODE_ENV"
  yarn $1
  popd > /dev/null
done
