#!/usr/bin/env ruby
# frozen_string_literal: true

exit 0 if ENV['DISABLE_RUBOCOP'] == '1'

require_relative './linter'
require 'optparse'

linter_options = {
  linter_name: "Rubocop",
  file_regex: %r{(?:\.e?rb|\.rake|\.gemspec|/[^./]+)$},
  format: "rubocop",
  command: "bin/rubocop",
  campsite_mode: false,
  append_files_to_command: true,
  severe_levels: [],
  default_boyscout_mode: false,
  heavy_mode_proc: proc do |ruby_files|
    args = ruby_files
    args_index = ARGV.index('--')
    if args_index
      args.concat(ARGV[(args_index + 1)..-1])
    end
    RuboCop::CLI.new.run(args)
  end
}
no_fail = false

OptionParser.new do |opts|
  opts.on("--heavy") { linter_options[:heavy_mode] = true }
  opts.on("--boy-scout") { linter_options[:boyscout_mode] = true }
  opts.on("--plugin PLUGIN") { |v| linter_options[:plugin] = v }
  opts.on("--no-fail-on-offense") { |v| no_fail = true }
end.parse!

rlint = Linter.new(linter_options)
exit 1 if !rlint.run && !no_fail
