#!/usr/bin/env ruby
require File.expand_path('../../config/boot',  __FILE__)

# Rails.env doesn't yet work here
if RAILS_ENV == "development" && ENV['BARE_SERVER'] != '1'
  dj = ENV["SCRIPT_SERVER_NO_JOBS"] != "1"
  if dj
    puts "Starting delayed jobs worker process. Pass SCRIPT_SERVER_NO_JOBS=1 to disable."
    dj_pid = fork {
      require(Rails.root+"config/environment.rb")
      Dir.chdir(Rails.root)
      Delayed::Pool.new(["run", "--no-tail"]).run
    }
    at_exit do
      Process.kill("INT", dj_pid)
    end
  else
    puts "Not starting a delayed jobs worker process."
  end

  guard = ENV["SCRIPT_SERVER_NO_GUARD"] != "1"
  if guard
    puts "Starting guard. Pass SCRIPT_SERVER_NO_GUARD=1 to disable."
    Thread.new do
      child_stdin, guard_stdin = IO.pipe
      guard_pid = fork do
        STDIN.reopen(child_stdin)
        guard_stdin.close
        exec "bundle exec guard"
      end
      child_stdin.close
      at_exit do
        Process.kill("INT", guard_pid)
      end
      Thread.new do
        loop do
          # pass on any return keypress to guard in a way that doesn't interfere with ruby-debug
          line = STDIN.readline
          if line.chomp == ""
            guard_stdin.puts ""
          end
        end
      end
    end
  else
    puts "Not starting guard."
  end

  if dj && guard
    puts "Pass BARE_SERVER=1 to disable both jobs and guard."
  end
end

require 'commands/server'
