#!/usr/bin/env ruby
if ARGV.any? { |arg| %w[--drb -X --generate-options -G --help -h --version -v].include?(arg) }
  require 'rubygems' unless ENV['NO_RUBYGEMS']
else
  gem 'test-unit', '1.2.3'
  ENV["RAILS_ENV"] ||= 'test'
  require File.expand_path(File.dirname(__FILE__) + "/../config/environment") unless defined?(Rails)
end

require 'rspec/autorun'
#make sure ARGV which is a filelist gets flattened and passed
#correctly this solution just runs the first file
exit ::RSpec::Core::Runner.run(ARGV)




