#!/usr/bin/env ruby
# frozen_string_literal: true

require_relative "linter"

linter_options = {
  linter_name: "stylelint",
  file_regex: /\.s?css$/,
  format: "stylelint",
  command: "node_modules/.bin/stylelint",
  campsite_mode: false,
  append_files_to_command: true
}

stylelint = Linter.new(linter_options)
stylelint.run
