#!/usr/bin/env ruby
# frozen_string_literal: true

require_relative "../gems/tatl_tael/lib/tatl_tael"
require "yaml"
require_relative "linter"

# # load personal config
require "dotenv"
Dotenv.load

linter_options = {
  linter_name: "tatl_tael",
  skip_file_size_check: true,
  skip_wips: false,
  custom_comment_generation: true,
  generate_comment_proc: proc do |**config|
    TatlTael::Linters.comments(**config)
  end,
  auto_correct: ENV["AUTO_CORRECT_LINTERS"]
}

Linter.new(linter_options).run
