source 'https://rubygems.org'

gemspec
gem 'simplecov', '0.8.2', :require => false
gem 'simplecov-rcov', '0.2.3', :require => false

gem 'i18n_extraction', path: '../i18n_extraction'
gem 'utf8_cleaner', path: '../utf8_cleaner'
