# frozen_string_literal: true

source "https://rubygems.org"

gemspec

gem "bookmarked_collection", path: "../bookmarked_collection"
gem "canvas_cassandra", path: "../canvas_cassandra"
gem "cassandra-cql", "1.2.3", github: "kreynolds/cassandra-cql", ref: "02b5abbe441a345c051a180327932566fd66bb36"
gem "config_file", path: "../config_file"
gem "json_token", path: "../json_token"
gem "paginated_collection", path: "../paginated_collection"
