# frozen_string_literal: true

source "https://rubygems.org"

gemspec

gem "bookmarked_collection", path: "../bookmarked_collection"
gem "config_file", path: "../config_file"
gem "json_token", path: "../json_token"
gem "paginated_collection", path: "../paginated_collection"

eval_gemfile("../gemfile_prefix.rb")

gem "rspec", "~> 3.12"
gem "simplecov", "~> 0.22"
gem "sqlite3"
