source 'https://rubygems.org'

# Specify your gem's dependencies in canvas_cassandra.gemspec
gemspec

gem 'cassandra-cql', '1.2.1', :github => 'kreynolds/cassandra-cql', :ref => 'd100be075b04153cf4116da7512892a1e8c0a7e4'
