# frozen_string_literal: true

source "https://rubygems.org"

gemspec

gem "cassandra-cql", "1.2.3", github: "kreynolds/cassandra-cql", ref: "02b5abbe441a345c051a180327932566fd66bb36"
gem "config_file", path: "../config_file"
