class CreateProjectScores86Table < ActiveRecord::Migration

  tag :predeploy
  def change
    orig_column_names = [
       'Student ID',
       'Student Name',
       'Student Email',
       'Total Score -- Capstone Challenge',
       'Category 1 Average -- Capstone Challenge',
       'Category 2 Average -- Capstone Challenge',
       'Category 3 Average -- Capstone Challenge',
       '1.1. Presenters identify users’ needs based in their own empathy research. -- Capstone Challenge',
       '1.2. Presenters clearly define the problem. -- Capstone Challenge',
       '1.3. Presenters explain why it is important to address the problem. -- Capstone Challenge',
       '1.4. Presenters pitch their top design solution and explain how their prototype solves the given problem. -- Capstone Challenge',
       '1.5. Presenters describe the feedback they received when testing their prototype and how they iterated to improve the prototype. -- Capstone Challenge',
       '1.6. Design solution is original and provides a unique value-add unlike other solutions that have been built. -- Capstone Challenge',
       '1.7.	Design solution is feasible. -- Capstone Challenge',
       '1.8. Presenters describe what realistic specific next steps they will take to implement their solution. -- Capstone Challenge',
       '2.1. Language and posture match the level of formality and demonstrate positivity curiosity respect and humility. -- Capstone Challenge',
       '2.10. Fellows do not read from slides/notes or sound robotic. -- Capstone Challenge',
       '2.11. I feel connected to the presenters and/or the content (e.g. through compelling data use of story or other techniques to connect to the audience). -- Capstone Challenge',
       '2.2. Presentation opens with a team introduction including names Braven cohort and closes by thanking the audience and evaluators. -- Capstone Challenge',
       '2.3. Presentation opens with an engaging hook to grab the audiences attention. -- Capstone Challenge',
       '2.4. Presentation tells a story of the overall arc of the cohorts design thinking process - where did the cohort start what did it work through and where did it end? -- Capstone Challenge',
       '2.5. All presenters are dressed appropriately in business casual attire (no jeans). -- Capstone Challenge',
       '2.6. All cohort members contribute to the presentation (e.g. Clearly planned roles). -- Capstone Challenge',
       '2.7. Presenters speak with minimal verbal tics and fillers. -- Capstone Challenge',
       '2.8. The presentation concludes with a clear final summary of the main points. -- Capstone Challenge',
       '2.9. The presentation does not exceed 7 minutes. -- Capstone Challenge',
       '3.1 No spelling or grammatical errors. -- Capstone Challenge',
       '3.2 Color and font choices are consistent throughout. -- Capstone Challenge',
       '3.3 Formatting is consistent throughout (e.g. Title capitalization use and positioning of bullets consistency with left vs. center justification alignment of figures etc.) -- Capstone Challenge',
       '3.4 Slides are not crowded with text or images. -- Capstone Challenge',
       '3.5. The slides support the oral presentation by effectively visualizing the spoken content. -- Capstone Challenge',
       'Total Score -- Complete second 1:1 with your Leadership Coach',
       'Total Score -- Course Participation - Synthesize',
       'Total Score -- Course Participation - Empathize',
       'Total Score -- Course Participation - Ideate & Prototype',
       'Total Score -- Course Participation - Live Your Legacy',
       'Total Score -- Course Participation - Prepare for Capstone Challenge Presentations',
       'Total Score -- Course Participation - Prepare for the Design Thinking Sprint',
       'Total Score -- Course Participation - Present Effectively',
       'Total Score -- Hustle to Career Project - NLU Part 2',
       'Category 1 Average -- Hustle to Career Project - NLU Part 2',
       'Category 2 Average -- Hustle to Career Project - NLU Part 2',
       '1.1 Develops a professional online brand through LinkedIn profile. -- Hustle to Career Project - NLU Part 2',
       '1.10 Email includes all the necessary components to make it strong. -- Hustle to Career Project - NLU Part 2',
       '1.11 Email is professional and concise. -- Hustle to Career Project - NLU Part 2',
       '1.12 Elevator pitch includes all necessary components. -- Hustle to Career Project - NLU Part 2',
       '1.13 Pitches self in a compelling and influential way. -- Hustle to Career Project - NLU Part 2',
       '1.14 Email is free of spelling and grammatical errors. -- Hustle to Career Project - NLU Part 2',
       '1.15 Conducts two informational interviews. -- Hustle to Career Project - NLU Part 2',
       '1.16 Plans how to leverage this connection. -- Hustle to Career Project - NLU Part 2',
       '1.17 Reflects meaningfully on the informational interviews with a growth mindset. -- Hustle to Career Project - NLU Part 2',
       '1.18 Attends one networking event and meets new professional contacts. -- Hustle to Career Project - NLU Part 2',
       '1.19 Plans how to leverage new contacts. -- Hustle to Career Project - NLU Part 2',
       '1.2 Writes a LinkedIn profile summary that includes all the necessary components. -- Hustle to Career Project - NLU Part 2',
       '1.20 Reflects meaningfully on the event with a growth mindset. -- Hustle to Career Project - NLU Part 2',
       '1.3 Writes a strong compelling LinkedIn summary that invites people to get in touch with you. -- Hustle to Career Project - NLU Part 2',
       '1.4 Completes education section of profile. -- Hustle to Career Project - NLU Part 2',
       '1.5 Completes experience section of profile. -- Hustle to Career Project - NLU Part 2',
       '1.6 Includes skills and endorsements on profile. -- Hustle to Career Project - NLU Part 2',
       '1.7 Develops extensive professional network on LinkedIn. -- Hustle to Career Project - NLU Part 2',
       '1.8 Makes an effort to set apart from the crowd. -- Hustle to Career Project - NLU Part 2',
       '1.9 Profile is free of spelling and grammatical errors. -- Hustle to Career Project - NLU Part 2',
       '2.1 Responds to the Tell me about yourself question with compelling experience about fit for role. -- Hustle to Career Project - NLU Part 2',
       '2.2 Responds to the Tell me about yourself question concisely and with focus. -- Hustle to Career Project - NLU Part 2',
       '2.3 Speaks with professional polish while answering the Tell me about yourself question. -- Hustle to Career Project - NLU Part 2',
       '2.4 Participates in mock interviews with professionals. -- Hustle to Career Project - NLU Part 2',
       '2.5 Writes a heartfelt thank you email to interviewer. -- Hustle to Career Project - NLU Part 2',
       '2.6 Thank you email is free of spelling and grammatical errors. -- Hustle to Career Project - NLU Part 2',
       '2.7 Reflects meaningfully on the interviews with a growth mindset. -- Hustle to Career Project - NLU Part 2',
       'Total Score -- Learning Lab Engagement - Capstone Challenge Kickoff',
       'Total Score -- Learning Lab Engagement - Capstone Challenge Presentations',
       'Total Score -- Learning Lab Engagement - Synthesize',
       'Total Score -- Learning Lab Engagement - Design Thinking Sprint',
       'Total Score -- Learning Lab Engagement - Emphatize',
       'Total Score -- Learning Lab Engagement - Ideate & Prototype',
       'Total Score -- Learning Lab Engagement - Live Your Legacy',
       'Total Score -- Learning Lab Engagement - Rehearse',
       'Total Score -- Live your Legacy Project',
       'Category 1 Average -- Live your Legacy Project',
       'Category 2 Average -- Live your Legacy Project',
       '1.1 Adds Capstone Challenge to resume as meaningful accomplishment. -- Live your Legacy Project',
       '1.10 Completes extra sections of resume as needed. -- Live your Legacy Project',
       '1.11 Resume is free of spelling and grammatical errors. -- Live your Legacy Project',
       '1.12 Meaningfully reflects on how incorporated feedback and improved resume. -- Live your Legacy Project',
       '1.2 Fills one page. -- Live your Legacy Project',
       '1.3 Formats resume professionally. -- Live your Legacy Project',
       '1.4 Completes Education section of resume. -- Live your Legacy Project',
       '1.5 Completes Experience section of resume. -- Live your Legacy Project',
       '1.6 Includes relevant coursework  and projects. -- Live your Legacy Project',
       '1.7 All other experiences (other than coursework and projects) included are relevant and demonstrate commitment. -- Live your Legacy Project',
       '1.8 Presents bulleted lists with strong action verbs under each experience. -- Live your Legacy Project',
       '1.9 Highlights impact in Experience section. -- Live your Legacy Project',
       '2.1 Knows him/herself and what is important to him/her. -- Live your Legacy Project',
       '2.2 Explains impact Braven had on him/her. -- Live your Legacy Project',
       '2.3 Describes the kind of impact s/he wants to have on others. -- Live your Legacy Project',
       '2.4 Determines what s/he will do in life. -- Live your Legacy Project',
       '2.5 Engages meaningfully with reflection. -- Live your Legacy Project',
       'Total Score -- Post-Accelerator Survey',
       'Total Score -- 4/16 Work Block Engagement - Capstone Challenge Kickoff',
       'Total Score -- 5/23 Work Block Engagement - Capstone Challenge Presentations',
       'Total Score -- 4/30 Work Block Engagement - Synthesize',
       'Total Score -- 4/9 Work Block Engagement - Design Thinking Sprint',
       'Total Score -- 4/23 Work Block Engagement - Empathize',
       'Total Score -- 5/7 Work Block Engagement - Ideate & Prototype',
       'Total Score -- 6/4 Work Block Engagement - Live Your Legacy',
       'Total Score -- 5/21 Work Block Engagement - Rehearse',
       'Total Score -- Capstone Challenge: Teamwork',
       'Category 4 Average -- Capstone Challenge: Teamwork',
       '4.1 Actively contributed to team success. -- Capstone Challenge: Teamwork',
       '4.2 Met deadlines and fulfilled responsibilities in a timely manner. -- Capstone Challenge: Teamwork',
       '4.3 Gave feedback to others to help them be more successful and productive. -- Capstone Challenge: Teamwork',
       '4.4 Embraced different perspectives on the team with openness and a sense of possibility. -- Capstone Challenge: Teamwork',
       'Total Score -- 5/14 Work Block Engagement - Refine and Prepare to Present',
       'Total Score -- Learning Lab Engagement - Refine and Prepare to Present',
       'Total Score -- Learning Lab 11 Impact Survey',
       'Total Score -- Learning Lab 12 Impact Survey',
       'Total Score -- Learning Lab 13 Impact Survey',
       'Total Score -- Learning Lab 14 Impact Survey',
       'Total Score -- Learning Lab 15 Impact Survey',
       'Total Score -- Learning Lab 16 Impact Survey',
       'Total Score -- Learning Lab 17 Impact Survey',
       'Total Score -- Learning Lab 18 Impact Survey',
       'Total Score -- Learning Lab 19 Impact Survey'
    ]

    create_table :course86_project_scores do |t|
      orig_column_names.each do |col_name|

        new_name = col_name.downcase.gsub(/[^0-9a-z]/, '_').to_sym
        if ['Student Name', 'Student Email'].member? col_name then
          t.string new_name
        else
          t.integer new_name
        end
      end
    end
  end
end
