---
quiz_log_auditing:
  state: allowed
  display_name:
    features.quiz_log_auditing: Quiz Log Auditing
  description:
    quiz_log_auditing_desc: |-
      Enable the tracking of events for a quiz submission, and the ability
            to view a log of those events once a submission is made.
  applies_to: Course
