---
pendo_extended:
  applies_to: Account
  type: setting
  state: hidden
  display_name: Pendo Extended Metadata
  description: When enabled, includes additional metadata information for Pendo
  shadow: true
institutional_tags:
  type: setting
  state: hidden
  applies_to: RootAccount
  shadow: true
  display_name: Institutional Tags
  description: Create user tags at the root account level.
