# Append `:docker-compose.spring.yml` to COMPOSE_FILE in `.env`
# invoke a console with `docker-compose run --rm web bin/rails console`
# or with specs: `docker-compose run --rm web bin/rspec spec/path/to/file_spec.rb`
version: '2.3'
services:
  web:
    environment:
      SPRING_TMP_PATH: tmp
      SPRING_SOCKET: tmp/spring.sock
      SPRING_PIDFILE: tmp/spring.pid
    depends_on:
      - spring

  spring:
    build: .
    command: bundle exec spring server
    volumes:
      - code:/usr/src/app
      - bundler:/home/docker/.bundler/
      - canvas-docker-gems:/home/docker/.gem/
      - yarn-cache:/home/docker/.cache/yarn
    environment:
      RAILS_ENV: development
      ENCRYPTION_KEY: facdd3a131ddd8988b14f6e4e01039c93cfa0160
      SPRING_TMP_PATH: tmp
      SPRING_SOCKET: tmp/spring.sock
      SPRING_PIDFILE: tmp/spring.pid
