# to use this add docker-compose/js-tests.override.yml
# to your COMPOSE_FILE var in .env

version: '2.3'
services:
  js-tests:
    build: ./docker-compose/karma
    volumes:
      - code:/usr/src/app
      - yarn-cache:/home/docker/.cache/yarn
    environment:
      NODE_ENV: CI
    command: yarn run test:karma:watch:headless
