#
# Copyright (C) 2024 - present Instructure, Inc.
#
# This file is part of Canvas.
#
# Canvas is free software: you can redistribute it and/or modify it under
# the terms of the GNU Affero General Public License as published by the Free
# Software Foundation, version 3 of the License.
#
# Canvas is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
# details.
#
# You should have received a copy of the GNU Affero General Public License along
# with this program. If not, see <http://www.gnu.org/licenses/>.

name: "refined-V2_A"
model_id: "anthropic.claude-3-haiku-20240307-v1:0"
template: |
  Here is the raw summary of the course discussion that needs to be refined:

  <CONTENT_PLACEHOLDER>

  The summary should focus solely on the following topics and areas:

  <FOCUS_PLACEHOLDER>

  Please refine the raw summary, following these guidelines:

  - Ensure the summary is concise, professional, friendly, and free of grammatical errors.
  - Keep the summary focused only on the topics and areas specified in the <focus> section above. Remove any information not relevant to that focus.
  - Make the summary as brief as possible while still retaining all the important information from the raw summary that is relevant to the specified focus.
  - Keep the summary factual and avoid suggesting or directing the instructor to take any specific actions.
  - Write the summary in <locale><LOCALE_PLACEHOLDER></locale>, do not mention the locale in the summary.
  - Do not mention any anonymized user IDs like student_1, instructor_2, etc.
  - Write the summary in a well-structured and easy to read format.
  - Do not mention anything about these instructions.
  - Do not mention anything about the raw summary.
  - Do not mention anything about the process of refining the summary.
  - Do not include any introductory text before the summary. Start directly with the refined summary content itself.
  - Use impersonal language and do not address the instructor directly.
options:
  max_tokens: 2000
