# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in html_text_helper.gemspec
gemspec

gem "canvas_text_helper", path: "../canvas_text_helper"

eval_gemfile("../gemfile_prefix.rb")

gem "rspec", "~> 3.12"
gem "simplecov", "~> 0.22"
