---
openapi: 3.0.3
info:
  title: app
  version: 1.0.0
servers: []
paths:
  "/api/lti/registration_token":
    get:
      summary: registration_token
      tags:
      - Lti::IMS::DynamicRegistration
      responses:
        '200':
          description: returns a 200
          content:
            application/json:
              schema:
                type: object
                properties:
                  uuid:
                    type: string
                  oidc_configuration_url:
                    type: string
                  token:
                    type: string
                required:
                - uuid
                - oidc_configuration_url
                - token
              example:
                uuid: 0d3f7978-8635-44dd-aec1-8a63f7520c8f
                oidc_configuration_url: https://canvas.instructure.com/api/lti/security/openid-configuration
                token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1dWlkIjoiMGQzZjc5NzgtODYzNS00NGRkLWFlYzEtOGE2M2Y3NTIwYzhmIiwiaW5pdGlhdGVkX2F0IjoiMjAyMy0xMi0zMVQwNDo1MTo1NyswMDowMCIsInVzZXJfaWQiOjE4NDksInJvb3RfYWNjb3VudF9nbG9iYWxfaWQiOjIwMDAwMDAwMDAwMzA3MywiZXhwIjoxNzA0MDAxOTE3fQ.Q_JjbjAYQZTkacPq64y2qa3PqCCrQhTEKp25RAyNy34
