/*
 * Copyright (C) 2024 - present Instructure, Inc.
 *
 * This file is part of Canvas.
 *
 * Canvas is free software: you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License as published by the Free
 * Software Foundation, version 3 of the License.
 *
 * Canvas is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
 * A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License along
 * with this program. If not, see <http://www.gnu.org/licenses/>.
 */

import React, {useContext, useState} from 'react'
import {TranslationControls} from '../../components/TranslationControls/TranslationControls'
import {View} from '@instructure/ui-view'
import {Heading} from '@instructure/ui-heading'
import {Text} from '@instructure/ui-text'
import {Flex} from '@instructure/ui-flex'
import {Button, IconButton} from '@instructure/ui-buttons'
import {SurveyLinkBox} from '@canvas/discussions/react/components/SurveyLinkBox/SurveyLinkBox'
import {useScope as useI18nScope} from '@canvas/i18n'
import {IconRefreshLine, IconEndLine, IconAiLine} from '@instructure/ui-icons'
import {DiscussionManagerUtilityContext} from '../../utils/constants'
import {TranslationTriggerModal} from '../../components/TranslationTriggerModal/TranslationTriggerModal'

export const DiscussionTranslationModuleContainer = ({isAnnouncement}) => {
  const I18n = useI18nScope('discussions_posts')
  const [isModalOpen, setModalOpen] = useState(false)
  const [selectedLanguage, setSelectedLanguage] = useState()
  const [isLanguageNotSelectedError, setIsLanguageNotSelectedError] = useState(false)
  const [isLanguageAlreadyActiveError, setIsLanguageAlreadyActiveError] = useState(false)

  const translationControlsRef = React.createRef()
  const {
    translateTargetLanguage,
    setTranslateTargetLanguage,
    setShowTranslationControl,
    entryTranslatingSet,
  } = useContext(DiscussionManagerUtilityContext)

  const closeTranslationModule = () => {
    if (translateTargetLanguage) {
      setModalOpen(true)
    } else {
      setShowTranslationControl(false)
    }
  }

  const closeModalAndKeepTranslations = () => {
    setModalOpen(false)
    setShowTranslationControl(false)
  }

  const closeModalAndRemoveTranslations = () => {
    setModalOpen(false)
    setShowTranslationControl(false)
    setTranslateTargetLanguage(null)
  }

  const resetTranslationsModule = () => {
    translationControlsRef.current?.reset()
    setTranslateTargetLanguage(null)
    setIsLanguageNotSelectedError(false)
    setIsLanguageAlreadyActiveError(false)
  }

  const translateDiscussion = () => {
    if (!selectedLanguage) {
      setIsLanguageNotSelectedError(true)
      return
    }

    if (selectedLanguage === translateTargetLanguage) {
      setIsLanguageAlreadyActiveError(true)
      return
    }

    setTranslateTargetLanguage(selectedLanguage)
  }

  const title = isAnnouncement ? I18n.t('Translate Announcement') : I18n.t('Translate Discussion')

  return (
    <View
      position="relative"
      borderColor="primary"
      as="div"
      borderRadius="medium"
      borderWidth="small"
      padding="large"
      margin="0 0 small 0"
    >
      <TranslationTriggerModal
        isModalOpen={isModalOpen}
        isAnnouncement={isAnnouncement}
        closeModal={() => {
          setModalOpen(false)
        }}
        closeModalAndKeepTranslations={closeModalAndKeepTranslations}
        closeModalAndRemoveTranslations={closeModalAndRemoveTranslations}
      />
      <Heading level="h3">
        {title}
        <span style={{float: 'right'}}>
          <IconButton
            size="small"
            onClick={closeTranslationModule}
            withBackground={false}
            withBorder={false}
            screenReaderLabel={I18n.t('Close translations module')}
          >
            <IconEndLine />
          </IconButton>
        </span>
      </Heading>
      <Text color="secondary" size="small">
        {I18n.t(
          'This translation is generated by AI. Please note that the output may not always be accurate.',
        )}
      </Text>
      <View as="div" margin="medium 0 x-small 0">
        <label id="translate-select-label">
          <Text weight="bold">{I18n.t('Translate to')}</Text>
        </label>
      </View>
      <Flex direction="row" alignItems="start" gap="small" wrap="wrap">
        <Flex.Item>
          <TranslationControls
            ref={translationControlsRef}
            isLanguageNotSelectedError={isLanguageNotSelectedError}
            onSetIsLanguageNotSelectedError={setIsLanguageNotSelectedError}
            isLanguageAlreadyActiveError={isLanguageAlreadyActiveError}
            onSetIsLanguageAlreadyActiveError={setIsLanguageAlreadyActiveError}
            onSetSelectedLanguage={languageId => {
              setSelectedLanguage(languageId)
            }}
          />
        </Flex.Item>
        <Flex.Item>
          <Button
            onClick={translateDiscussion}
            disabled={entryTranslatingSet.size > 0}
            margin="0 small 0 0"
            renderIcon={<IconAiLine />}
            color="primary"
          >
            {I18n.t('Translate')}
          </Button>
          <Button
            onClick={resetTranslationsModule}
            renderIcon={<IconRefreshLine />}
            disabled={entryTranslatingSet.size > 0}
          >
            {I18n.t('Reset')}
          </Button>
        </Flex.Item>
      </Flex>
      <SurveyLinkBox
        text={I18n.t('What do you think of *Discussion Translate*?', {
          wrappers: [`<strong>$1</strong>`],
        })}
        marginTop="medium"
      />
    </View>
  )
}
